export const defaultMeta = {
  siteName: process.env.NEXT_PUBLIC_APP_NAME,
  title: "Build interfaces with precision components",
  description:
    "The comprehensive React component library for mission-critical applications. Type-safe, accessible, and composable.",
  canonicalUrl: process.env.NEXT_PUBLIC_APP_URL,
  ogType: "website",
  keywords: [
    "react component library",
    "web design",
    "UI components",
    "responsive design",
    "modern design",
    "reusable components",
    "front-end development",
    "web development",
    "user interface",
    "beautiful UI",
    "stunning components",
    "zero effort",
    "copy-paste components",
    "web elements",
    "website building blocks",
    "web templates",
    "UI kits",
    "design resources",
    "front-end tools",
    "web design inspiration",
    "web design trends",
    "web design solutions",
    "design tools",
    "web design assets",
    "UI design",
    "UX design",
    "web design components",
    "web UI",
    "responsive web components",
    "modern web components",
    "beautiful web components",
    "stunning web UI",
    "web design elements",
    "web UI kits",
    "responsive UI kits",
    "modern UI kits",
    "front-end web development",
    "web development resources",
    "web components library",
    "web UI library",
    "web design library",
    "no-code web design",
    "easy web design",
    "web design made easy",
    "easy web development",
    "no-code web development",
    "web design for beginners",
    "web development for beginners",
    "drag-and-drop web design",
    "visual web design",
    "visual web development",
    "WYSIWYG web design",
    "WYSIWYG web development",
    "web design platforms",
    "web development platforms",
    "web design tools",
    "web development tools",
    "web design software",
    "web development software",
    "web design apps",
    "web development apps",
    "web design plugins",
    "web development plugins",
    "web design extensions",
    "web development extensions",
    "web design integrations",
    "web development integrations",
    "web design services",
    "web development services",
    "web design agencies",
    "web development agencies",
    "web design freelancers",
    "web development freelancers",
    "web design consultants",
    "web development consultants",
    "web design experts",
    "web development experts",
    "web design professionals",
    "web development professionals",
    "web design gurus",
    "web development gurus",
    "web design maestros",
    "web development maestros",
    "web design masters",
    "web development masters",
    "LibravelUI",
    "LibravelUI web components",
    "LibravelUI UI components",
    "LibravelUI responsive design",
    "LibravelUI modern design",
    "LibravelUI reusable components",
    "LibravelUI web development",
    "LibravelUI user interface",
    "LibravelUI beautiful UI",
    "LibravelUI stunning components",
    "LibravelUI web templates",
    "LibravelUI UI kits",
    "LibravelUI design resources",
  ],
  ogImage:
    "https://url-to-your-image-this-is-a-default-value-for-optional-parameter",
  twitterCard: "summary_large_image",
};
